name: Build and run Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Chọn phiên bản Node.js phù hợp

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./path/to/your/project  # Đảm bảo đúng thư mục chứa package.json

      - name: Build Docker image
        run: |
          docker build -t my-node-app .

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 my-node-app
